Deprecate getlog

diff --git a/getlog b/getlog
--- a/getlog
+++ b/getlog
@@ -1,8 +1,3 @@
 #!/usr/bin/env bash
-FNAME=$( ssh lvuser@10.18.16.2 'ls -rt zodiac* ' 2>/dev/null | tail -1 )
-
-echo "Getting $FNAME"
-
-scp lvuser@10.18.16.2:$FNAME .
-
-badlogvis -o $FNAME
+echo "ERROR: getlog is deprecated. Use logutil fetch instead."
+exit 1
